import logo1 from "../../Resources/Icons/Accu-Icons/1.png";
import logo2 from "../../Resources/Icons/Accu-Icons/2.png";
import logo3 from "../../Resources/Icons/Accu-Icons/3.png";
import logo4 from "../../Resources/Icons/Accu-Icons/4.png";
import logo5 from "../../Resources/Icons/Accu-Icons/5.png";
import logo6 from "../../Resources/Icons/Accu-Icons/6.png";
import logo7 from "../../Resources/Icons/Accu-Icons/7.png";
import logo8 from "../../Resources/Icons/Accu-Icons/8.png";
//import logo10 from "../../Resources/Icons/Accu-Icons/10.png";
import logo11 from "../../Resources/Icons/Accu-Icons/11.png";
import logo12 from "../../Resources/Icons/Accu-Icons/12.png";
import logo13 from "../../Resources/Icons/Accu-Icons/13.png";
import logo14 from "../../Resources/Icons/Accu-Icons/14.png";
import logo15 from "../../Resources/Icons/Accu-Icons/15.png";
import logo16 from "../../Resources/Icons/Accu-Icons/16.png";
import logo17 from "../../Resources/Icons/Accu-Icons/17.png";
import logo18 from "../../Resources/Icons/Accu-Icons/18.png";
import logo19 from "../../Resources/Icons/Accu-Icons/19.png";
import logo20 from "../../Resources/Icons/Accu-Icons/20.png";
import logo21 from "../../Resources/Icons/Accu-Icons/21.png";
import logo22 from "../../Resources/Icons/Accu-Icons/22.png";
import logo23 from "../../Resources/Icons/Accu-Icons/23.png";
import logo24 from "../../Resources/Icons/Accu-Icons/24.png";
import logo25 from "../../Resources/Icons/Accu-Icons/25.png";
import logo26 from "../../Resources/Icons/Accu-Icons/26.png";
import logo29 from "../../Resources/Icons/Accu-Icons/29.png";
import logo30 from "../../Resources/Icons/Accu-Icons/30.png";
import logo31 from "../../Resources/Icons/Accu-Icons/31.png";
import logo32 from "../../Resources/Icons/Accu-Icons/32.png";
import logo33 from "../../Resources/Icons/Accu-Icons/33.png";
import logo34 from "../../Resources/Icons/Accu-Icons/34.png";
import logo35 from "../../Resources/Icons/Accu-Icons/35.png";
import logo36 from "../../Resources/Icons/Accu-Icons/36.png";
import logo37 from "../../Resources/Icons/Accu-Icons/37.png";
import logo38 from "../../Resources/Icons/Accu-Icons/38.png";
import logo39 from "../../Resources/Icons/Accu-Icons/39.png";
import logo40 from "../../Resources/Icons/Accu-Icons/40.png";
import logo41 from "../../Resources/Icons/Accu-Icons/41.png";
import logo42 from "../../Resources/Icons/Accu-Icons/42.png";
import logo43 from "../../Resources/Icons/Accu-Icons/43.png";
import logo44 from "../../Resources/Icons/Accu-Icons/44.png";


const AccuIcon = (icon) => {
  switch (icon) {
    case '1': return logo1;
    break;
    case '2': return logo2;
    break;
    case '3': return logo3;
    break;
    case '4': return logo4;
    break;
    case '5': return logo5;
    break;
    case '6': return logo6;
    break;
    case '7': return logo7;
    break;
    case '8': return logo8;
    break;
    // case '10': return {logo10};
    // break;
    case '11': return logo11;
    break;
    case '12': return logo12;
    break;
    case '13': return logo13;
    break;
    case '14': return logo14;
    break;
    case '15': return logo15;
    break;
    case '16': return logo16;
    break;
    case '17': return logo17;
    break;
    case '18': return logo18;
    break;
    case '19': return logo19;
    break;
    case '20': return logo20;
    break;
    case '21': return logo21;
    break;
    case '22': return logo22;
    break;
    case '23': return logo23;
    break;
    case '24': return logo24;
    break;
    case '25': return logo25;
    break;
    case '26': return logo26;
    break;
    case '29': return logo29;
    break;
    case '30': return logo30;
    break;
    case '31': return logo31;
    break;
    case '32': return logo32;
    break;
    case '33': return logo33;
    break;
    case '34': return logo34;
    break;
    case '35': return logo35;
    break;
    case '36': return logo36;
    break;
    case '37': return logo37;
    break;
    case '38': return logo38;
    break;
    case '39': return logo39;
    break;
    case '40': return logo40;
    break;
    case '41': return logo41;
    break;
    case '42': return logo42;
    break;
    case '43': return logo43;
    break;
    case '44': return logo44;
    break;
    default: return null
  }
}

export default AccuIcon;